# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question/'),
        ),
    ]
