# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0003_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('current_status', models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('closed', 'closed')], default='pending', max_length=7)),
                ('questions', models.ManyToManyField(to='quizgame.Question')),
            ],
        ),
    ]
