# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0005_auto_20181208_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
