# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0006_auto_20181208_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_queston',
            new_name='current_question',
        ),
    ]
