# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0008_auto_20181208_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_question_obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_question', to='quizgame.Question'),
        ),
        migrations.AlterField(
            model_name='player',
            name='questions',
            field=models.ManyToManyField(related_name='question_set', to='quizgame.Question'),
        ),
    ]
