# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0010_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', models.CharField(max_length=100)), ('B', models.CharField(max_length=100)), ('C', models.CharField(max_length=100)), ('D', models.CharField(max_length=100))], default='A', max_length=1),
        ),
    ]
