# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0011_auto_20181209_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nr_of_questions',
            field=models.IntegerField(default=10),
        ),
    ]
