# Generated by Django 2.2 on 2020-08-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0014_auto_20200816_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_question_obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_question', to='quizgame.Question'),
        ),
    ]
